/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcedimentosSlugRouteImport } from './routes/procedimentos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosSlugRoute = ProcedimentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProcedimentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/procedimentos': typeof ProcedimentosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/procedimentos': typeof ProcedimentosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/procedimentos': typeof ProcedimentosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/galeria'
    | '/procedimentos'
    | '/sobre'
    | '/procedimentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/galeria'
    | '/procedimentos'
    | '/sobre'
    | '/procedimentos/$slug'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/galeria'
    | '/procedimentos'
    | '/sobre'
    | '/procedimentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  ProcedimentosRoute: typeof ProcedimentosRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos/$slug': {
      id: '/procedimentos/$slug'
      path: '/$slug'
      fullPath: '/procedimentos/$slug'
      preLoaderRoute: typeof ProcedimentosSlugRouteImport
      parentRoute: typeof ProcedimentosRoute
    }
  }
}

interface ProcedimentosRouteChildren {
  ProcedimentosSlugRoute: typeof ProcedimentosSlugRoute
}

const ProcedimentosRouteChildren: ProcedimentosRouteChildren = {
  ProcedimentosSlugRoute: ProcedimentosSlugRoute,
}

const ProcedimentosRouteWithChildren = ProcedimentosRoute._addFileChildren(
  ProcedimentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  ProcedimentosRoute: ProcedimentosRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
